#lang ivy1.7

include quic_server_test

export frame.max_stream_id.handle
export frame.max_stream_data.handle
export frame.stream_blocked.handle

before frame.max_stream_data.handle(f:frame.max_stream_data,src:ip.endpoint,dst:ip.endpoint,scid:cid,dcid:cid,e:encryption_level) {
    require f.pos > 32;
}

before frame.stream_blocked.handle(f:frame.stream_blocked,src:ip.endpoint,dst:ip.endpoint,scid:cid,dcid:cid,e:encryption_level) {
    require f.pos > 32;
}
