#lang ivy1.7

include quic_server_test

export frame.max_stream_id.handle
export frame.max_stream_data.handle
export frame.max_data.handle
#export frame.stream_blocked.handle
export frame.rst_stream.handle
attribute frame.rst_stream.handle.weight = "0.02"
attribute frame.max_stream_id.handle.weight = "0.02"
attribute frame.max_stream_data.handle.weight = "0.02"
attribute frame.max_data.handle.weight = "0.02"


# export frame.connection_close.handle
# attribute frame.connection_close.handle.weight = "0.02"

#export frame.application_close.handle
#attribute frame.application_close.handle.weight = "0.02"

export frame.stop_sending.handle

before frame.max_stream_data.handle(f:frame.max_stream_data,scid:cid,dcid:cid,e:quic_packet_type) {
    if _generating {
        require f.pos = 32 | f.pos = 16;
    }
}

before frame.stream_blocked.handle(f:frame.stream_blocked,scid:cid,dcid:cid,e:quic_packet_type) {
    if _generating {
        require f.pos > 32;
    }
}

before frame.max_data.handle(f:frame.max_data,scid:cid,dcid:cid,e:quic_packet_type) {
    if _generating {
        require f.pos = 2048 | f.pos = 40;
    }
}
