#lang ivy1.6

    type t

    relation man(X:t)
    relation mortal(X:t)
    individual socrates : t

    schema socrates_species = {
        #------------------
	property man(socrates)
    }

    property man(socrates)
    proof socrates_species

    schema mortality_of_man = {
        property [prem] man(X)
        #---------------
        property mortal(X)
    }

    property [mortsoc] mortal(socrates)
    proof mortality_of_man



