#!/bin/bash

tests='enum1 client_server1  client_server4  detect_transitive
client_server2  client_server5  enum1
client_server3  client_server6  transitive
projections'

sh_tests='tilelink_unit_test.sh'

trap '{ echo "Exiting on SIGINT." ; exit 1; }' INT

errors=0
for x in $tests; do
    echo $x ...
    if timeout 100 python $x.py > $x.log 2>&1 ; then
        echo PASS
    else
        echo FAIL
        (( errors += 1 )) 
    fi
done


for x in $sh_tests; do
    echo $x ...
    if timeout 100 ./$x ; then
        echo PASS
    else
        echo FAIL
        (( errors += 1 )) 
    fi
done


echo "errors: $errors"