#lang ivy1.7

include udp_impl
include tls_msg

# This file provides the interface to the test locale. This includes
# two services: TLS 1.3 and UDP.

object tls_api = {
    instance id : unbounded_sequence
    instance lower : tls_lower_intf(id,stream_data)
    instance upper : tls_intf(id,stream_pos,stream_data,lower,tls_extensions,tls_ser,pkt_num)
}    

instance net : udp_impl(endpoint_id,prot.arr,quic_prot_ser,quic_prot_deser)

