#!/bin/bash

# Copyright (c) Microsoft Corporation. All Rights Reserved.

# Clear all outputs from all notebooks

ipython nbconvert --to notebook --ClearOutputPreprocessor.enabled=True --inplace *.ipynb
