
# ivy_termtab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xd0#\x94\x06\xe3\xe3[\xe1$ \xfaCY\xfa\xb8\x0f'
    
_lr_action_items = {'OLD':([0,5,8,9,10,14,25,],[2,2,2,2,2,2,2,]),'SYMBOL':([0,2,5,8,9,10,12,14,15,25,],[3,3,3,3,3,3,19,3,23,3,]),'TIMES':([1,3,4,6,7,11,13,16,17,18,19,20,21,23,24,26,],[10,-1,-4,-8,-6,-7,10,10,10,-11,-5,-15,10,-3,-2,10,]),'COLON':([4,],[12,]),'PLUS':([1,3,4,6,7,11,13,16,17,18,19,20,21,23,24,26,],[8,-1,-4,-8,-6,-7,8,-9,-10,-11,-5,-15,8,-3,-2,8,]),'LPAREN':([0,3,5,7,8,9,10,11,14,23,24,25,],[5,-1,5,14,5,5,5,14,5,-3,-2,5,]),'VARIABLE':([0,5,8,9,10,14,25,],[4,4,4,4,4,4,4,]),'RPAREN':([3,4,6,7,11,13,14,16,17,18,19,20,21,22,23,24,26,],[-1,-4,-8,-6,-7,20,-12,-9,-10,-11,-5,-15,-13,24,-3,-2,-14,]),'COMMA':([3,4,6,7,11,14,16,17,18,19,20,21,22,23,24,26,],[-1,-4,-8,-6,-7,-12,-9,-10,-11,-5,-15,-13,25,-3,-2,-14,]),'MINUS':([1,3,4,6,7,11,13,16,17,18,19,20,21,23,24,26,],[9,-1,-4,-8,-6,-7,9,9,-10,-11,-5,-15,9,-3,-2,9,]),'DOT':([3,7,11,23,24,],[-1,15,15,-3,-2,]),'$end':([1,3,4,6,7,11,16,17,18,19,20,23,24,],[0,-1,-4,-8,-6,-7,-9,-10,-11,-5,-15,-3,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'var':([0,5,8,9,10,14,25,],[6,6,6,6,6,6,6,]),'term':([0,5,8,9,10,14,25,],[1,13,16,17,18,21,26,]),'terms':([14,],[22,]),'aterm':([0,2,5,8,9,10,14,25,],[7,11,7,7,7,7,7,7,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> term","S'",1,None,None,None),
  ('aterm -> SYMBOL','aterm',1,'p_aterm_symbol','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',16),
  ('aterm -> aterm LPAREN terms RPAREN','aterm',4,'p_aterm_aterm_terms','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',21),
  ('aterm -> aterm DOT SYMBOL','aterm',3,'p_term_term_dot_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',35),
  ('var -> VARIABLE','var',1,'p_var_variable','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',40),
  ('var -> VARIABLE COLON SYMBOL','var',3,'p_var_variable_colon_symbol','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',45),
  ('term -> aterm','term',1,'p_term_aterm','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',50),
  ('term -> OLD aterm','term',2,'p_aterm_old_symbol','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',54),
  ('term -> var','term',1,'p_term_var','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',59),
  ('term -> term PLUS term','term',3,'p_term_term_PLUS_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',65),
  ('term -> term MINUS term','term',3,'p_term_term_MINUS_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',70),
  ('term -> term TIMES term','term',3,'p_term_term_TIMES_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',75),
  ('terms -> <empty>','terms',0,'p_terms','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',81),
  ('terms -> term','terms',1,'p_terms_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',85),
  ('terms -> terms COMMA term','terms',3,'p_terms_terms_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',89),
  ('term -> LPAREN term RPAREN','term',3,'p_term_lp_term_lp','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',95),
  ('vars -> var','vars',1,'p_vars_var','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',99),
  ('vars -> vars COMMA var','vars',3,'p_vars_vars_comma_var','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',103),
  ('app -> SYMBOL','app',1,'p_app_symbol','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',110),
  ('app -> SYMBOL LPAREN terms RPAREN','app',4,'p_app_symbol_lp_terms_rp','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',115),
  ('app -> term infix term','app',3,'p_app_term_infix_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',120),
  ('apps -> app','apps',1,'p_apps_app','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',126),
  ('apps -> apps COMMA app','apps',3,'p_apps_apps_app','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',130),
  ('atom -> SYMBOL','atom',1,'p_atom_symbol','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',137),
  ('atom -> SYMBOL LPAREN terms RPAREN','atom',4,'p_atom_symbol_lp_terms_rp','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',142),
  ('atoms -> atom','atoms',1,'p_atoms_atom','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',147),
  ('atoms -> atoms COMMA atom','atoms',3,'p_atoms_atoms_atom','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',151),
  ('lit -> atom','lit',1,'p_lit_atom','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',158),
  ('lit -> SYMBOL EQ SYMBOL','lit',3,'p_lit_term_eq_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',163),
  ('lit -> SYMBOL TILDAEQ SYMBOL','lit',3,'p_lit_term_tildaeq_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',168),
  ('lit -> TILDA lit','lit',2,'p_lit_tilda_atom','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',173),
  ('relop -> EQ','relop',1,'p_relop_eq','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',178),
  ('relop -> LE','relop',1,'p_relop_le','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',182),
  ('relop -> LT','relop',1,'p_relop_lt','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',186),
  ('relop -> GE','relop',1,'p_relop_ge','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',190),
  ('relop -> GT','relop',1,'p_relop_gt','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',194),
  ('infix -> PLUS','infix',1,'p_infix_plus','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',198),
  ('infix -> MINUS','infix',1,'p_infix_minus','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',202),
  ('infix -> TIMES','infix',1,'p_infix_times','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',206),
  ('fmla -> term','fmla',1,'p_fmla_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',212),
  ('fmla -> term relop term','fmla',3,'p_fmla_term_relop_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',216),
  ('fmla -> term TILDAEQ term','fmla',3,'p_fmla_term_tildaeq_term','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',221),
  ('fmla -> LPAREN fmla RPAREN','fmla',3,'p_fmla_lparen_fmla_rparen','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',226),
  ('fmla -> TRUE','fmla',1,'p_fmla_true','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',230),
  ('fmla -> FALSE','fmla',1,'p_fmla_false','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',235),
  ('fmla -> TILDA fmla','fmla',2,'p_fmla_not_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',240),
  ('fmla -> fmla AND fmla','fmla',3,'p_fmla_fmla_and_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',245),
  ('fmla -> fmla OR fmla','fmla',3,'p_fmla_fmla_or_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',254),
  ('fmla -> fmla ARROW fmla','fmla',3,'p_fmla_fmla_arrow_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',265),
  ('fmla -> fmla IFF fmla','fmla',3,'p_fmla_fmla_iff_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',270),
  ('fmla -> FORALL vars DOT fmla','fmla',4,'p_fmla_forall_vars_dot_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',275),
  ('fmla -> EXISTS vars DOT fmla','fmla',4,'p_fmla_exists_vars_dot_fmla','/home/mcmillan/projects/ivy/src/ivy/ivy_logic_parser.py',280),
]
