#lang ivy

header "ivy.h"

type bool
interpret bool -> ivy.native_bool

object ivy {
    
    type cint
    interpret cint -> ivy.native_int[int]
    
    type func
    type size_t

}
extern action ivy.put(c:ivy.cint)
extern action ivy.get returns (c:ivy.cint)
extern action ivy.resize(f:ivy.func,s:ivy.size_t) returns (f:ivy.func)
extern action ivy.getenv(name:ivy.func) returns (val:ivy.func)
extern action ivy.read_file(name:ivy.func,data:ivy.func) returns (data:ivy.func,ok:bool)

