#lang ivy

# This file contains modules to access system resources such as
# processes and environment variables.

# This module gives access to environement variable, where `str` is a
# type with string traits.

module environment(str) = {

    # The `get` action gets the value of an environment variable
    # `name` or returns the empty string if `name` is undefined.

    action get(name:str) returns (res:str) = {
	res := cast(ivy.getenv(cast(name)))
    }
}    
